### ISSUE TITLE
release文件中不包含版本

### ISSUE THREAD

**Issue by yaoge123** [iori2333/Mira#10]
建议在releases的文件名中不包含版本号，就是每次文件名均相同，这样便于脚本自动更新

**Comment by iori2333** [comment]
ok

**Comment by wojiushixiaobai** [comment]
😂 正常情况下包含版本号比较容易区分。

如果没有处理好旧版本文件，文件名就变成 `mira-release.zip.1` or `mira-release（1）.zip` 等。当然脚本里面在保存时重命名或者先判断是否存在文件也行。

总之无伤大雅。
