### ISSUE TITLE
openSUSE 镜像使用帮助中的指令会禁用全部软件源

### ISSUE THREAD

**Issue by magiclogy-** [iori2333/Mira#17]
帮助文档中写道使用命令`sudo zypper mr -da`禁用官方软件源，然而实际的效果是禁用全部软件源，这可能会导致大量软件包被错误卸载（例如nvidia驱动）。
建议修改成使用tag来禁用软件源。对于openSUSE Tumbleweed，使用下面的指令来禁用这些软件源：
```
zypper mr -d repo-oss
zypper mr -d repo-non-oss
```

**Comment by iori2333** [comment]
收到，之后会修改（考试周太忙请见谅）
