### ISSUE TITLE
conda install 提示错误

### ISSUE THREAD

**Issue by Janewendo** [iori2333/Mira#21]
安装的anaconda
.condarc为：
channels:
  - https://mirror.nju.edu.cn/anaconda/cloud/conda-forge
  - https://mirror.nju.edu.cn/anaconda/cloud/pytorch
  - https://mirror.nju.edu.cn/anaconda/pkgs/main
  - https://mirror.nju.edu.cn/anaconda/pkgs/r
  - https://mirror.nju.edu.cn/anaconda/pkgs/msys2

show_channel_urls: true

执行语句：conda install -c conda-forge pcraster
但报错：
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/linux-64/current_repodata.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2b1cbb49f9e8>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"))

**Comment by iori2333** [comment]
这里只接受前端issue，请前往[后端issue](https://github.com/nju-lug/NJU-Mirror-Issue/issues)提问。
