### ISSUE TITLE
Armbian apt update 总是失败

### ISSUE THREAD

**Issue by young40** [iori2333/Mira#22]
`Hit:1 http://mirror.nju.edu.cn/ubuntu-ports impish InRelease
Hit:2 http://mirror.nju.edu.cn/ubuntu-ports impish-security InRelease
Hit:3 http://mirror.nju.edu.cn/ubuntu-ports impish-updates InRelease
Hit:4 http://mirror.nju.edu.cn/ubuntu-ports impish-backports InRelease
Get:5 https://mirror.nju.edu.cn/armbian impish InRelease [26.9 kB]
Get:6 https://mirror.nju.edu.cn/armbian impish/impish-desktop armhf Packages [383 B]
Get:7 https://mirror.nju.edu.cn/armbian impish/impish-utils armhf Packages [5,143 B]
Ign:7 https://mirror.nju.edu.cn/armbian impish/impish-utils armhf Packages
Ign:9 https://mirror.nju.edu.cn/armbian impish/main arm64 Packages
Ign:10 https://mirror.nju.edu.cn/armbian impish/impish-utils arm64 Packages
Ign:11 https://mirror.nju.edu.cn/armbian impish/main armhf Packages
Get:7 https://mirror.nju.edu.cn/armbian impish/impish-utils armhf Packages [5,143 B]
Err:7 https://mirror.nju.edu.cn/armbian impish/impish-utils armhf Packages
  File has unexpected size (10510 != 5143). Mirror sync in progress? [IP: 210.28.130.3 443]
  Hashes of expected file:
   - Filesize:5143 [weak]
   - SHA512:70b2bfbd0132da87d730d940980606776d1a1dcb6594ff2dc72250ea86e34cf66dc21bf39f7a7651d4ae9dc826ca04f7e88a3f88a2fdb20d97728d272fb4d6d6
   - SHA256:f2f4a2a60c7c8cbf6eb8879dc05e99241d0676ec18b67f6ba65089374fd06c13
   - SHA1:408404ac3977ba25bcbcf41987c62885eece68d9 [weak]
   - MD5Sum:2008703029ef6cfd46e11910a353e0df [weak]
  Release file created at: Tue, 01 Feb 2022 17:28:59 +0000
Get:9 https://mirror.nju.edu.cn/armbian impish/main arm64 Packages [192 kB]
Err:9 https://mirror.nju.edu.cn/armbian impish/main arm64 Packages

Get:10 https://mirror.nju.edu.cn/armbian impish/impish-utils arm64 Packages [5,398 B]
Err:10 https://mirror.nju.edu.cn/armbian impish/impish-utils arm64 Packages

Get:11 https://mirror.nju.edu.cn/armbian impish/main armhf Packages [137 kB]
Err:11 https://mirror.nju.edu.cn/armbian impish/main armhf Packages

Reading package lists... Done
E: Failed to fetch https://mirror.nju.edu.cn/armbian/dists/impish/impish-utils/binary-armhf/Packages.gz  File has unexpected size (10510 != 5143). Mirror sync in progress? [IP: 210.28.130.3 443]
   Hashes of expected file:
    - Filesize:5143 [weak]
    - SHA512:70b2bfbd0132da87d730d940980606776d1a1dcb6594ff2dc72250ea86e34cf66dc21bf39f7a7651d4ae9dc826ca04f7e88a3f88a2fdb20d97728d272fb4d6d6
    - SHA256:f2f4a2a60c7c8cbf6eb8879dc05e99241d0676ec18b67f6ba65089374fd06c13
    - SHA1:408404ac3977ba25bcbcf41987c62885eece68d9 [weak]
    - MD5Sum:2008703029ef6cfd46e11910a353e0df [weak]
   Release file created at: Tue, 01 Feb 2022 17:28:59 +0000
E: Failed to fetch https://mirror.nju.edu.cn/armbian/dists/impish/main/binary-arm64/Packages.gz
E: Failed to fetch https://mirror.nju.edu.cn/armbian/dists/impish/impish-utils/binary-arm64/Packages.gz
E: Failed to fetch https://mirror.nju.edu.cn/armbian/dists/impish/main/binary-armhf/Packages.gz
E: Some index files failed to download. They have been ignored, or old ones used instead.`

希望可以修一下, 万分感谢.

**Comment by iori2333** [comment]
这种一般属于同步中，一般稍等些时日后即可恢复。
此外，这里只接受前端issue，请前往[后端issue](https://github.com/nju-lug/NJU-Mirror-Issue/issues)提问。
